//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapYE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.ReportComments = new HashSet<ReportComment>();
        }
    
        public int CommentId { get; set; }
        public int SenderId { get; set; }
        public string Content { get; set; }
        public System.DateTime Dateposted { get; set; }
        public string Image_1 { get; set; }
        public int ItemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportComment> ReportComments { get; set; }
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
