//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapYE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportChat
    {
        public int ReportMsgId { get; set; }
        public int UserID { get; set; }
        public string Description_1 { get; set; }
        public int ChatId { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual User User { get; set; }
    }
}
